### ISSUE TITLE
提供服务请求模板组管理功能

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/wecube-plugins-taskman#4]
**作为**
<用户角色>
**我想要**
<服务请求模板组的创建、删除、修改、查询四个功能>
**从而**
<进行服务请求模板组的管理操作>

**附加**
#### 2. 服务请求模板组在创建时，
  - 需要用户输入唯一的组名和描述
  - 需要用户选定一个或多个角色作为该组的管理角色，可选的管理角色来源于wecube
  - 需要记录服务请求模板组的创建用户、创建时间、最后更新用户、最后更新时间。  
#### 3. 服务请求模板组在查询时，  
  - 需要展示以下信息：组名，管理角色，描述  
#### 4. 服务请求模板组在修改时，  
  - 可修改组名、管理角色、描述
  - 修改成功后需要更新 最后更新用户、最后更新时间  
#### 5. 服务请求模板组在删除时，  
  - 数据库采用软删除的方式，即不删数据，只把数据状态更新为已删除

**Comment by pobu168** [comment]
Done
